name: Ko Builder

permissions:
  contents: read

env:
  # Builder
  BUILDER_BINARY: builder

###################################################################
#                                                                 #
#            Input and output argument definitions                #
#                                                                 #
###################################################################
on:
  workflow_call:
    secrets:
      password:
        description: "Password to log in the registry"
        required: true
    inputs:
      envs:
        description: "Environment variables to pass to the builder"
        required: true
        type: string
      args:
        description: "Arguments to pass to the 'ko publish'"
        required: false
        type: string
      username:
        description: "Username to log in the registry"
        required: true
        type: string
    outputs:
      image:
        description: "The full path to the generated container image"
        value: ${{ jobs.build-release.outputs.image }}


jobs:
  detect-env:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed to detect the current reusable repository and ref.
      contents: read
    outputs:
      builder_repo: ${{ steps.detect.outputs.builder_repo }}
      builder_ref: ${{ steps.detect.outputs.builder_ref }}
    steps:
      - name: Detect the builder ref
        id: detect
        shell: bash
        run: | 
          status_code=$(curl -sS -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=${{ github.repository }}/ko-builder" -o jwt.json -w '%{http_code}')
          if [[ $status_code -ne 200 ]]; then
              error_msg=$(jq -r .message jwt.json 2>/dev/null || echo 'unknown error')
              echo "Failed to get OIDC token from GitHub, response $status_code: $error_msg"
              exit 1;
          fi
          export WORKFLOW_REF=$(cat jwt.json | jq -r '.value' | cut -d "." -f2 | base64 -d | jq -r '.job_workflow_ref')
          if [ -z $WORKFLOW_REF ]; then
            echo "OIDC token parsing failure: job_workflow_ref could not be retrieved"
            exit 1;
          fi
          echo "::set-output name=builder_repo::$(echo $WORKFLOW_REF | cut -d "@" -f1 | cut -d '/' -f1-2)"
          echo "::set-output name=builder_ref::$(echo $WORKFLOW_REF | cut -d "@" -f2)"
          
  builder:
    runs-on: ubuntu-latest
    needs: detect-env
    permissions:
      contents: read
    outputs:
      builder-sha256: ${{ steps.builder-gen.outputs.sha256 }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v2.3.4
        with:
          fetch-depth: 0
          repository: "${{ needs.detect-env.outputs.builder_repo }}"
          ref: "${{ needs.detect-env.outputs.builder_ref }}"

      - name: Set up golang environment
        uses: actions/setup-go@f6164bd8c8acb4a71fb2791a8b6c4024ff038dab # v2.1.3
        with:
          go-version: 1.17

      - name: Download dependencies
        shell: bash
        run: |
          set -euo pipefail
          #TODO(reproducible)
          go mod vendor

      # TODO(hermeticity) OS-level.
      # - name: Disable hermeticity
      # uses: slsa/hermeticity@xxx
      #   with:
      #     to-state: enabled

      - name: Build builder
        shell: bash
        id: builder-gen
        env:
          BUILDER_BINARY: "${{ env.BUILDER_BINARY }}"
        run: |
            set -euo pipefail

            # https://go.dev/ref/mod#build-commands.
            go build -mod=vendor -o "$BUILDER_BINARY"
            BUILDER_DIGEST=$(sha256sum "$BUILDER_BINARY" | awk '{print $1}')
            echo "::set-output name=sha256::$BUILDER_DIGEST"
            echo "hash of $BUILDER_BINARY is $BUILDER_DIGEST"

      - name: Upload the builder
        uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535 # v2.3.1
        with:
          name: "${{ env.BUILDER_BINARY }}"
          path: "${{ env.BUILDER_BINARY }}"
          if-no-files-found: error
          retention-days: 5
      
  ###################################################################
  #                                                                 #
  #                 Build dry to resolve variables                  #
  #                                                                 #
  ###################################################################
  build-dry:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    needs: [builder]
    env:
      UNTRUSTED_ARGS: "${{ inputs.args }}"
      UNTRUSTED_ENVS: "${{ inputs.envs }}"
      BUILDER_HASH: "${{ needs.builder.outputs.builder-sha256 }}"
    outputs:
      command: ${{ steps.build-dry.outputs.command }}
      envs: ${{ steps.build-dry.outputs.envs }}
      registry: ${{ steps.build-dry.outputs.registry }}
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v2.3.4
        with:
          fetch-depth: 0
      
      - name: Download builder
        uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741 # v2.1.0
        with:
          name: "${{ env.BUILDER_BINARY }}"
      
      - name: Verify builder
        env:
          BUILDER_BINARY: "${{ env.BUILDER_BINARY }}"
        run: |
          set -euo pipefail

          echo "hash of builder should be $BUILDER_HASH"
          COMPUTED_HASH=$(sha256sum "$BUILDER_BINARY" | awk '{print $1}')
          echo "builder hash computed is $COMPUTED_HASH"

          # Compare hashes. Explicit exit to be safe.
          # TODO: remove the builder as well.
          echo "$BUILDER_HASH $BUILDER_BINARY" | sha256sum --strict --check --status || exit -2
    
          # Make the builder executable.
          chmod a+x "$BUILDER_BINARY"
  
      - name: Dry build
        id: build-dry
        env:
          BUILDER_BINARY: "${{ env.BUILDER_BINARY }}"
        run: |
          set -euo pipefail
          
          # TODO: verify hash
          echo "running the builder $BUILDER_BINARY with hash $BUILDER_HASH"
          echo ./"$BUILDER_BINARY" build --dry \
            --args "$UNTRUSTED_ARGS" \
            --envs "$UNTRUSTED_ENVS"

          # echo ./"$BUILDER_BINARY" build --dry --args "$UNTRUSTED_ARGS" --envs "$UNTRUSTED_ENVS"
          # ./"$BUILDER_BINARY" build --dry --args "$UNTRUSTED_ARGS" --envs "$UNTRUSTED_ENVS"
          
          if [[ -z "$UNTRUSTED_ARGS" ]]
          then
              if [[ -z "$UNTRUSTED_ENVS" ]]
              then
                echo ./"$BUILDER_BINARY" build --dry
                ./"$BUILDER_BINARY" build --dry
              else
                  echo ./"$BUILDER_BINARY" build --dry --envs "$UNTRUSTED_ENVS"
                 ./"$BUILDER_BINARY" build --dry --envs "$UNTRUSTED_ENVS"
              fi
          else
              if [[ -z "$UNTRUSTED_ENVS" ]]
              then
                echo ./"$BUILDER_BINARY" build --dry --args "$UNTRUSTED_ARGS"
                 ./"$BUILDER_BINARY" build --dry --args "$UNTRUSTED_ARGS"
              else
                  echo ./"$BUILDER_BINARY" build --dry --args "$UNTRUSTED_ARGS" --envs "$UNTRUSTED_ENVS"
                 ./"$BUILDER_BINARY" build --dry --args "$UNTRUSTED_ARGS" --envs "$UNTRUSTED_ENVS"
              fi
          fi
  
  ###################################################################
  #                                                                 #
  #                       Build the project                         #
  #                                                                 #
  ###################################################################
  build-release:
    runs-on: ubuntu-latest
    needs: [builder,build-dry]
    permissions:
      contents: read
      packages: write
    env:
      UNTRUSTED_PASSWORD: ${{ secrets.password }}
      UNTRUSTED_USERNAME: ${{ inputs.username }}
      UNTRUSTED_ARGS: "${{ inputs.args }}"
      UNTRUSTED_ENVS: "${{ inputs.envs }}"
      UNTRUSTED_REGISTRY: "${{ needs.build-dry.outputs.registry }}"
      BUILDER_HASH: "${{ needs.builder.outputs.builder-sha256 }}"
    outputs:
      image: ${{ steps.build-push.outputs.image }}
    steps:
      - uses: actions/setup-go@f6164bd8c8acb4a71fb2791a8b6c4024ff038dab # v2.1.3

      - name: Checkout the repository
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v2.3.4
        with:
          fetch-depth: 0
  
      - name: Download builder
        uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741 # v2.1.0
        with:
          name: "${{ env.BUILDER_BINARY }}"

      - name: Verify builder
        env:
          BUILDER_BINARY: "${{ env.BUILDER_BINARY }}"
        run: |
          set -euo pipefail

          echo "hash of builder should be $BUILDER_HASH"
          COMPUTED_HASH=$(sha256sum "$BUILDER_BINARY" | awk '{print $1}')
          echo "builder hash computed is $COMPUTED_HASH"

          # Compare hashes. Explicit exit to be safe.
          # TODO: remove the builder as well.
          echo "$BUILDER_HASH $BUILDER_BINARY" | sha256sum --strict --check --status || exit -2
    
          # Make the builder executable.
          chmod a+x "$BUILDER_BINARY"
      
      # Note: downlaoading and pinning the download seems better
      # than adding this dependency. Need to look how the install works
      # remko/dsadmin/blob/7a6939179bc56b1be28cada040f2b4a148e3e14a/.github/workflows/publish-release.yml
      - name: Setup Ko
        uses: imjasonh/setup-ko@v0.4
    
      - name: Login
        run: |
          set -euo pipefail
                    
          echo "login to $REGISTRY"

          ko login "$REGISTRY" -u "$UNTRUSTED_USERNAME" -p "$UNTRUSTED_PASSWORD"

      - name: Build and push
        id: build-push
        env:
          BUILDER_BINARY: "${{ env.BUILDER_BINARY }}"
        run: |
          set -euo pipefail

          pwd
          ls -la

          IMAGE=""
          if [[ -z "$UNTRUSTED_ARGS" ]]
          then
              if [[ -z "$UNTRUSTED_ENVS" ]]
              then
                echo ./"$BUILDER_BINARY" build
                IMAGE=$(./"$BUILDER_BINARY" build | tail -1)
              else
                echo ./"$BUILDER_BINARY" build --envs "$UNTRUSTED_ENVS"
                IMAGE=$(./"$BUILDER_BINARY" build --envs "$UNTRUSTED_ENVS"  | tail -1)
              fi
          else
              if [[ -z "$UNTRUSTED_ENVS" ]]
              then
                echo ./"$BUILDER_BINARY" build --args "$UNTRUSTED_ARGS"
                IMAGE=$(./"$BUILDER_BINARY" build --args "$UNTRUSTED_ARGS"  | tail -1)
              else
                echo ./"$BUILDER_BINARY" build --args "$UNTRUSTED_ARGS" --envs "$UNTRUSTED_ENVS"
                IMAGE=$(./"$BUILDER_BINARY" build --args "$UNTRUSTED_ARGS" --envs "$UNTRUSTED_ENVS"  | tail -1)
              fi
          fi
          
          echo "image generated is: $IMAGE"
          echo "::set-output name=image::$IMAGE"
  
  ###################################################################
  #                                                                 #
  #                 Generate the SLSA provenance                    #
  #                                                                 #
  ###################################################################
  provenance:
    runs-on: ubuntu-latest
    needs: [builder,build-dry,build-release]
    permissions:
      packages: write
      contents: read
      id-token: write
    env:
      UNTRUSTED_IMAGE: "${{ needs.build-release.outputs.image }}"
      UNTRUSTED_COMMAND: "${{ needs.build-dry.outputs.command }}"
      UNTRUSTED_ENVS: "${{ needs.build-dry.outputs.envs }}"
      UNTRUSTED_REGISTRY: "${{ needs.build-dry.outputs.registry }}"
      UNTRUSTED_PASSWORD: "${{ secrets.password }}"
      UNTRUSTED_USERNAME: "${{ inputs.username }}"
      BUILDER_HASH: "${{ needs.builder.outputs.builder-sha256 }}"
      GITHUB_CONTEXT: "${{ toJSON(github) }}"
    steps:
      - name: Download builder
        uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741 # v2.1.0
        with:
          name: "${{ env.BUILDER_BINARY }}"

      - name: Verify builder
        env:
          BUILDER_BINARY: "${{ env.BUILDER_BINARY }}"
        run: |
          set -euo pipefail

          echo "hash of builder should be $BUILDER_HASH"
          COMPUTED_HASH=$(sha256sum "$BUILDER_BINARY" | awk '{print $1}')
          echo "builder hash computed is $COMPUTED_HASH"

          # Compare hashes. Explicit exit to be safe.
          # TODO: remove the builder as well.
          echo "$BUILDER_HASH $BUILDER_BINARY" | sha256sum --strict --check --status || exit -2
    
          # Make the builder executable.
          chmod a+x "$BUILDER_BINARY"

      - name: Generate predicate
        id: gen-predicate
        env:
          BUILDER_BINARY: "${{ env.BUILDER_BINARY }}"
        run: |
          set -euo pipefail
                    
          #TODO: generate PROJECT dynamically using the URL
          # testing. Use a local file containing provenance.
          IMAGE_SHA256=$(echo $UNTRUSTED_IMAGE | cut -d "@" -f2 | cut -d ":" -f2)
          IMAGE_NAME=$(echo $UNTRUSTED_IMAGE | cut -d "@" -f1)
                    
          echo "image is: $UNTRUSTED_IMAGE"

          echo "::set-output name=image::$UNTRUSTED_IMAGE"

          # Note: this will print the predice
          echo ./"$BUILDER_BINARY" predicate --artifact-name "$IMAGE_NAME" \
            --digest "$IMAGE_SHA256" --command "$UNTRUSTED_COMMAND" \
            --env "$UNTRUSTED_ENVS"

          ./"$BUILDER_BINARY" predicate --artifact-name "$IMAGE_NAME" \
            --digest "$IMAGE_SHA256" --command "$UNTRUSTED_COMMAND" \
            --env "$UNTRUSTED_ENVS"
          
      # Note: here we need packages permissions
      # TODO: here we may use each ecosystem's login action instead,
      # or use cosign login
      - uses: sigstore/cosign-installer@d6a3abf1bdea83574e28d40543793018b6035605
      - name: Login
        run: |
          set -euo pipefail
                    
          echo "login to $REGISTRY"

          cosign login "$REGISTRY" -u "$UNTRUSTED_USERNAME" -p "$UNTRUSTED_PASSWORD"
          
      - name: Upload
        env:
          UNTRUSTED_PREDICATE: "${{ steps.gen-predicate.outputs.predicate }}"
          UNTRUSTED_IMAGE: "${{ steps.gen-predicate.outputs.image }}"
        run: |
          set -euo pipefail
            
          echo cosign attest --predicate "$UNTRUSTED_PREDICATE" \
            --type "slsaprovenance" \
            --force \
            "$UNTRUSTED_IMAGE"
            
          COSIGN_EXPERIMENTAL=1 cosign attest --predicate "$UNTRUSTED_PREDICATE" \
            --type "slsaprovenance" \
             --force \
            "$UNTRUSTED_IMAGE"

          
         
